name: cuidapet
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^4.5.1+1
  mobx: ^2.0.6+1
  flutter_mobx: ^2.0.4
  asuka: ^2.0.0+1
  dio: ^4.0.6
  flutter_screenutil: ^5.3.1
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.8

  flutter_lints: ^1.0.0

flutter:

  uses-material-design: true