name: cuidapet
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_modular: ^5.0.3
  mobx: ^2.0.6
  flutter_mobx: ^2.0.3+1
  asuka: ^2.0.0
  dio: ^5.4.3+1
  flutter_screenutil: ^5.0.1+3
  cupertino_icons: ^1.0.4

  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  firebase_remote_config: ^4.3.8
  firebase_messaging: ^14.7.10
  # firebase_analytics: ^10.1.6

  flutter_dotenv: ^5.0.2
  logger: ^2.3.0

  shared_preferences: ^2.0.11
  
  flutter_secure_storage: ^8.1.0

  validatorless: ^1.2.1

  google_sign_in: ^6.1.4
  flutter_facebook_auth: ^5.0.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.0.5+2
  build_runner: ^2.1.8
  flutter_lints: ^2.0.2

# dependency_overrides:
#   firebase_core: ^1.14.1
#   firebase_remote_config: ^2.0.4
#   firebase_auth: 3.3.14


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - .env
  
  fonts:
    - family: CuidapetIcons
      fonts:
        - asset: assets/fonts/CuidapetIcons.ttf